language: cpp
sudo: required
dist: trusty
before_install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update
- sudo apt-get install g++-5 -y
compiler:
- g++
os:
- linux
before_script:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
- cmake .
script:
- make
- ./Alltest -d yes