language: cpp
sudo: required
dist: trusty

os:
- linux

compiler:
- gcc

evn:
- COMPILER=g++-4.9
- SPECIAL=valgrind

addons:
 apt:
  sources: ['ubuntu-toolchain-r-test']
  packages: [g++-4.9, valgrind]

script:
- cmake .
- make
- ./Alltest -d yes

after_success:
- make check-leak-test