language: cpp
sudo: required
dist: trusty
before_install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update
- sudo apt-get install g++-5 -y
compiler:
- g++
os:
- linux
script:
- cmake .
- make
- ./Alltest -d yes